// questions.js

const questions = {
    easy: [
       { question: "Quel est le plus grand océan ?", answers: ["Atlantique", "Indien", "Arctique", "Pacifique"], correct: "Pacifique" },
       { question: "Combien de continents sur Terre ?", answers: ["5", "6", "7", "8"], correct: "7" },
       { question: "Quel est l'élément chimique O ?", answers: ["Oxygène", "Or", "Ozone", "Osmium"], correct: "Oxygène" },
       { question: "Qui a écrit 'Les Misérables' ?", answers: ["Victor Hugo", "Zola", "Hugo Boss", "Jean-Paul Sartre"], correct: "Victor Hugo" },
       { question: "Quel est le plus long fleuve du monde ?", answers: ["Nil", "Amazonie", "Yangtsé", "Mississippi"], correct: "Nil" },
       // Jeux vidéo - facile
       { question: "Quel plombier est la mascotte de Nintendo ?", answers: ["Luigi", "Mario", "Sonic", "Link"], correct: "Mario" },
       { question: "Quel est le héros principal de 'The Legend of Zelda' ?", answers: ["Link", "Zelda", "Ganondorf", "Mario"], correct: "Link" },
       { question: "Quel jeu se joue avec des blocs à construire et casser ?", answers: ["Terraria", "Fortnite", "Minecraft", "Roblox"], correct: "Minecraft" },
       { question: "Dans quel jeu doit-on construire un fort pour survivre aux zombies ?", answers: ["Call of Duty", "Fortnite", "PUBG", "Apex Legends"], correct: "Fortnite" },
       { question: "Quel hérisson bleu court à toute vitesse ?", answers: ["Tails", "Knuckles", "Shadow", "Sonic"], correct: "Sonic" },
       { question: "Dans quel jeu visite-t-on une île peuplée d'animaux mignons ?", answers: ["Stardew Valley", "Animal Crossing", "Harvest Moon", "The Sims"], correct: "Animal Crossing" },
       { question: "Quel jeu de voiture est connu pour ses carapaces rouges et ses bananes ?", answers: ["Need for Speed", "Gran Turismo", "Mario Kart", "F-Zero"], correct: "Mario Kart" },
       { question: "Qui est le créateur de la série 'Super Smash Bros' ?", answers: ["Shigeru Miyamoto", "Masahiro Sakurai", "Hideo Kojima", "Gabe Newell"], correct: "Masahiro Sakurai" },
       { question: "Dans 'Minecraft', quel est l'objectif pour finir le jeu ?", answers: ["Battre le Wither", "Explorer le Nether", "Battre l'Ender Dragon", "Construire une maison"], correct: "Battre l'Ender Dragon" },
       { question: "Quel est le nom de la compagnie créatrice de 'League of Legends' ?", answers: ["Valve", "Riot Games", "Epic Games", "Blizzard"], correct: "Riot Games" },
       { question: "Quel jeu célèbre propose une bataille royale à 100 joueurs ?", answers: ["Valorant", "League of Legends", "Call of Duty", "Fortnite"], correct: "Fortnite" },
       { question: "Quel héros utilise un grappin dans les jeux *The Legend of Zelda* ?", answers: ["Link", "Ganondorf", "Mario", "Sora"], correct: "Link" },
       { question: "Quelle entreprise a créé la console PlayStation ?", answers: ["Sega", "Nintendo", "Sony", "Microsoft"], correct: "Sony" },
       { question: "Quel jeu met en scène des légumes et des zombies ?", answers: ["Overcooked", "Plants vs Zombies", "Slime Rancher", "Stardew Valley"], correct: "Plants vs Zombies" },
       { question: "Quel est le nom du personnage principal de *The Witcher* ?", answers: ["Link", "Geralt", "Kratos", "Ezio"], correct: "Geralt" },
       { question: "Quelle console est sortie avant la Nintendo Switch ?", answers: ["PS5", "Game Boy", "Wii U", "Xbox Series X"], correct: "Wii U" },
       { question: "Dans *Among Us*, quel est le rôle de celui qui sabote et tue ?", answers: ["Agent", "Imposteur", "Alien", "Saboteur"], correct: "Imposteur" },
       { question: "Quel studio a développé le jeu *Fortnite* ?", answers: ["Epic Games", "Valve", "Ubisoft", "EA"], correct: "Epic Games" },
       // Sport - facile
       { question: "Combien de joueurs sur le terrain dans une équipe de football ?", answers: ["9", "10", "11", "12"], correct: "11" },
       { question: "Quel footballeur est surnommé 'La Pulga' ?", answers: ["Cristiano Ronaldo", "Neymar", "Lionel Messi", "Mbappé"], correct: "Lionel Messi" },
       { question: "Dans quel sport utilise-t-on une batte et une balle ?", answers: ["Baseball", "Tennis", "Football", "Basketball"], correct: "Baseball" },
       { question: "Quel sport est associé au ring et aux gants ?", answers: ["Boxe", "Catch", "Karate", "Sumo"], correct: "Boxe" },
       { question: "Comment s'appelle la grande compétition mondiale de football ?", answers: ["Coupe UEFA", "Copa America", "Coupe du Monde", "Euro"], correct: "Coupe du Monde" },
       { question: "En catch, qui est 'The Undertaker' ?", answers: ["Un arbitre", "Un catcheur", "Un entraîneur", "Un commentateur"], correct: "Un catcheur" },
       { question: "Quel sport est Michael Jordan célèbre pour ?", answers: ["Football", "Baseball", "Basketball", "Tennis"], correct: "Basketball" },
       { question: "Dans quel sport marque-t-on des buts avec un stick ?", answers: ["Hockey sur glace", "Basketball", "Tennis", "Cricket"], correct: "Hockey sur glace" },
       { question: "Combien de points pour un touchdown au football américain ?", answers: ["3", "6", "7", "10"], correct: "6" },
       { question: "Comment s'appelle la plus grande course cycliste au monde ?", answers: ["Giro d'Italia", "Vuelta", "Tour de France", "Paris-Roubaix"], correct: "Tour de France" },
       ],

   medium: [
       // Moyennes (questions 6 à 10)
       { question: "Quel est le pays le plus peuplé du monde ?", answers: ["Chine", "Inde", "USA", "Indonésie"], correct: "Chine" },
       { question: "En quelle année l'homme a-t-il marché sur la lune ?", answers: ["1965", "1969", "1972", "1975"], correct: "1969" },
       { question: "Quel est le plus long fleuve d'Europe ?", answers: ["Danube", "Volga", "Rhône", "Loire"], correct: "Volga" },
       { question: "Combien d'os dans le corps humain adulte ?", answers: ["198", "206", "214", "230"], correct: "206" },
       { question: "Quel pays a inventé le papier ?", answers: ["Égypte", "Chine", "Grèce", "Inde"], correct: "Chine" },

       // Jeux vidéo - moyen
       { question: "Quel jeu vidéo a introduit pour la première fois le terme 'Metroidvania' ?", answers: ["Super Metroid", "Castlevania: Symphony of the Night", "Blaster Master", "Shadow Complex"], correct: "Castlevania: Symphony of the Night" },
       { question: "Quelle entreprise a racheté Bethesda en 2020 ?", answers: ["Sony", "Tencent", "Microsoft", "Embracer Group"], correct: "Microsoft" },
       { question: "Quel jeu indépendant a remporté le titre de jeu de l’année aux Game Awards 2021 ?", answers: ["Hades", "It Takes Two", "Death's Door", "Returnal"], correct: "It Takes Two" },
       { question: "Quel célèbre duo a cofondé le studio Naughty Dog ?", answers: ["Amy Hennig & Neil Druckmann", "Jason Rubin & Andy Gavin", "Cory Barlog & David Jaffe", "Mark Cerny & Shuhei Yoshida"], correct: "Jason Rubin & Andy Gavin" },
       { question: "Quelle console a été surnommée la 'Dreamcast Killer' ?", answers: ["PlayStation 2", "GameCube", "Xbox", "Nintendo 64"], correct: "PlayStation 2" },
       { question: "Dans 'The Legend of Zelda: Ocarina of Time', quel est l'instrument principal utilisé par Link ?", answers: ["Harpe", "Ocarina", "Flûte", "Guitare"], correct: "Ocarina" },
       { question: "Quel est le vrai prénom de Solid Snake dans 'Metal Gear Solid' ?", answers: ["David", "John", "Jack", "Chris"], correct: "David" },
       { question: "Dans quel jeu incarne-t-on un chasseur de monstres dans un monde ouvert, souvent en équipe ?", answers: ["Monster Hunter", "Dark Souls", "Elden Ring", "Bloodborne"], correct: "Monster Hunter" },
       { question: "Dans 'Overwatch', quel personnage est un gorille scientifique ?", answers: ["Winston", "Hanzo", "Sigma", "Reinhardt"], correct: "Winston" },
       { question: "Quel jeu propose de survivre sur une île après un crash d'avion, avec des ennemis cannibales ?", answers: ["The Forest", "Rust", "Subnautica", "ARK"], correct: "The Forest" },
       { question: "Dans 'Final Fantasy VII', comment s'appelle la société maléfique qui pompe l'énergie de la planète ?", answers: ["Shinra", "Umbrella", "Cerberus", "Avalanche"], correct: "Shinra" },
       { question: "Quel studio a développé 'The Witcher 3: Wild Hunt' ?", answers: ["CD Projekt Red", "Ubisoft", "Bethesda", "Bioware"], correct: "CD Projekt Red" },
       { question: "Dans quel jeu peut-on devenir un tueur de dragons appelé Dovahkiin ?", answers: ["Skyrim", "Dark Souls", "Dragon Age", "The Elder Scrolls Online"], correct: "Skyrim" },
       { question: "Comment s'appelle la ville de départ dans 'GTA: San Andreas' ?", answers: ["Los Santos", "Vice City", "Liberty City", "Las Venturas"], correct: "Los Santos" },
       { question: "Dans quel jeu la mécanique de voyage dans le temps est centrale et le protagoniste s'appelle Max ?", answers: ["Life is Strange", "Detroit: Become Human", "Heavy Rain", "Until Dawn"], correct: "Life is Strange" },
       { question: "Dans 'League of Legends', comment s'appelle le dragon qui donne un bonus à l'équipe ?", answers: ["Baron Nashor", "Dragon Ancien", "Gromp", "Herald of the Rift"], correct: "Dragon Ancien" },
       { question: "Dans 'Apex Legends', quel personnage est spécialisé dans la guérison ?", answers: ["Lifeline", "Wraith", "Bloodhound", "Octane"], correct: "Lifeline" },
       { question: "Dans 'Red Dead Redemption 2', comment s'appelle le protagoniste principal ?", answers: ["Arthur Morgan", "John Marston", "Dutch van der Linde", "Micah Bell"], correct: "Arthur Morgan" },
       { question: "Quel jeu propose une île infestée de zombies et un héros nommé Kyle Crane ?", answers: ["Dead Island", "Dying Light", "State of Decay", "Days Gone"], correct: "Dying Light" },
       { question: "Dans 'Pokémon', quel type est super efficace contre le type Eau ?", answers: ["Feu", "Plante", "Vol", "Psy"], correct: "Plante" },
       { question: "Dans quel jeu incarne-t-on Kratos, le dieu de la guerre ?", answers: ["Dark Souls", "God of War", "Assassin's Creed", "Ghost of Tsushima"], correct: "God of War" },
       { question: "Quel jeu propose une enquête narrative autour d'une boucle temporelle sur une station spatiale ?", answers: ["Outer Wilds", "Prey", "Dead Space", "Returnal"], correct: "Outer Wilds" },
       { question: "Quel jeu de FromSoftware se déroule dans un Japon alternatif du XVIe siècle ?", answers: ["Bloodborne", "Sekiro: Shadows Die Twice", "Elden Ring", "Tenchu"], correct: "Sekiro: Shadows Die Twice" },
       { question: "Quelle console a popularisé les cartouches de jeu dans les années 80 ?", answers: ["Atari 2600", "NES", "Sega Master System", "ColecoVision"], correct: "Atari 2600" },
       { question: "Quel jeu a été au cœur du premier grand tournoi e-sport : le 'Red Annihilation' en 1997 ?", answers: ["Doom", "StarCraft", "Quake", "Counter-Strike"], correct: "Quake" },
       { question: "Quel studio est à l’origine de la saga 'The Elder Scrolls' ?", answers: ["Bioware", "Obsidian", "Bethesda", "CD Projekt"], correct: "Bethesda" },
       { question: "Sur quelle console est sorti 'Super Mario 64' ?", answers: ["Super Nintendo", "Nintendo 64", "GameCube", "Wii"], correct: "Nintendo 64" },
       { question: "Qui est le créateur de 'Metal Gear Solid' ?", answers: ["Miyamoto", "Hideo Kojima", "Yoko Taro", "Shinji Mikami"], correct: "Hideo Kojima" },
       { question: "Quel est le premier jeu de type 'battle royale' à avoir explosé sur Twitch ?", answers: ["PUBG", "Apex Legends", "Fortnite", "H1Z1"], correct: "PUBG" },
       { question: "Quel streamer français est connu pour ses speedruns sur 'Zelda: Ocarina of Time' ?", answers: ["Ponce", "Gius", "RealMyop", "BaguetteNoir"], correct: "Gius" },
       { question: "Quel jeu d’arcade a été officiellement reconnu comme le premier e-sport avec des récompenses ?", answers: ["Pong", "Space Invaders", "Donkey Kong", "Pac-Man"], correct: "Space Invaders" },
       { question: "Quel studio est derrière le jeu VR 'Beat Saber' ?", answers: ["Superhot Team", "Harmonix", "Beat Games", "VRChat Inc."], correct: "Beat Games" },
       { question: "Quel jeu a remporté le Game of the Year aux Game Awards 2023 ?", answers: ["Baldur's Gate 3", "Zelda: Tears of the Kingdom", "Alan Wake II", "Spider-Man 2"], correct: "Baldur's Gate 3" },
       // Sport - moyen
       { question: "Quel footballeur argentin a inscrit 'la main de Dieu' contre l'Angleterre en 1986 ?", answers: ["Lionel Messi", "Gabriel Batistuta", "Diego Maradona", "Javier Zanetti"], correct: "Diego Maradona" },
       { question: "Quel footballeur a remporté le plus de Ballons d'Or ?", answers: ["Cristiano Ronaldo", "Pelé", "Lionel Messi", "Zinédine Zidane"], correct: "Lionel Messi" },
       { question: "Quel événement sportif majeur a lieu tous les 4 ans et rassemble des nations entières ?", answers: ["Coupe du monde", "Jeux olympiques", "Super Bowl", "Tour de France"], correct: "Jeux olympiques" },
       { question: "Quel catcheur a popularisé la prise 'RKO' ?", answers: ["Edge", "Randy Orton", "Brock Lesnar", "Roman Reigns"], correct: "Randy Orton" },
       { question: "Quel pays a remporté la Coupe du monde de football en 1998 ?", answers: ["Italie", "Allemagne", "France", "Brésil"], correct: "France" },
       { question: "En Formule 1, de quelle nationalité est Lewis Hamilton ?", answers: ["Américain", "Anglais", "Canadien", "Australien"], correct: "Anglais" },
       { question: "Quel joueur portugais est célèbre pour avoir joué au Real Madrid et à Manchester United ?", answers: ["Cristiano Ronaldo", "Luis Figo", "Bruno Fernandes", "Pepe"], correct: "Cristiano Ronaldo" },
       { question: "En catch, comment s'appelle le célèbre mouvement final de John Cena ?", answers: ["RKO", "Spear", "Attitude Adjustment", "Chokeslam"], correct: "Attitude Adjustment" },
       { question: "Quel pays a remporté la Coupe du Monde de football en 2018 ?", answers: ["Allemagne", "France", "Brésil", "Croatie"], correct: "France" },
       { question: "En NBA, pour quelle équipe Michael Jordan est-il devenu une légende ?", answers: ["Los Angeles Lakers", "Chicago Bulls", "Miami Heat", "Boston Celtics"], correct: "Chicago Bulls" },
       { question: "Dans quel sport pratique-t-on le Grand Chelem ?", answers: ["Golf", "Tennis", "Rugby", "Athlétisme"], correct: "Tennis" },
       { question: "Qui est surnommé 'The Undertaker' dans le catch ?", answers: ["Kane", "The Rock", "The Undertaker", "Stone Cold Steve Austin"], correct: "The Undertaker" },
       { question: "Combien de joueurs une équipe de football aligne-t-elle sur le terrain au début d'un match ?", answers: ["9", "10", "11", "12"], correct: "11" },
       { question: "En Formule 1, quel pilote britannique est septuple champion du monde ?", answers: ["Lewis Hamilton", "Jenson Button", "Nigel Mansell", "Sebastian Vettel"], correct: "Lewis Hamilton" },
       { question: "Quel pays organise les Jeux Olympiques de Paris 2024 ?", answers: ["Italie", "Allemagne", "France", "Espagne"], correct: "France" },
       { question: "Quel catcheur est célèbre pour sa prise appelée le '619' ?", answers: ["Rey Mysterio", "Edge", "Triple H", "Kurt Angle"], correct: "Rey Mysterio" },
       { question: "Combien de sets faut-il gagner pour remporter un match masculin en Grand Chelem au tennis ?", answers: ["2", "3", "4", "5"], correct: "3" },
       { question: "Quel est le surnom de Lionel Messi ?", answers: ["La Pulga", "El Niño", "El Tigre", "El Matador"], correct: "La Pulga" },
       { question: "Dans quel sport Usain Bolt est-il champion ?", answers: ["Natation", "Athlétisme", "Ski", "Cyclisme"], correct: "Athlétisme" },
       { question: "Comment s'appelle l'événement annuel principal de la WWE ?", answers: ["SummerSlam", "Royal Rumble", "Survivor Series", "WrestleMania"], correct: "WrestleMania" },
       { question: "Combien de points vaut un tir à trois points au basket ?", answers: ["2", "3", "4", "5"], correct: "3" },
       { question: "Quel joueur de tennis est surnommé 'le Taureau de Manacor' ?", answers: ["Federer", "Nadal", "Djokovic", "Murray"], correct: "Nadal" },
       { question: "Quel club anglais est surnommé 'The Reds' ?", answers: ["Arsenal", "Chelsea", "Manchester United", "Liverpool"], correct: "Liverpool" },
       { question: "Combien de sets faut-il gagner pour remporter un match en Grand Chelem (chez les hommes) ?", answers: ["2", "3", "4", "5"], correct: "3" },
   

   ],
   
   hard: [
          // Difficiles (questions 11 à 15)
       { question: "Quel est le plus grand désert du monde ?", answers: ["Sahara", "Arctique", "Gobi", "Atacama"], correct: "Sahara" },
       { question: "Qui a peint la Mona Lisa ?", answers: ["Van Gogh", "Léonard de Vinci", "Monet", "Picasso"], correct: "Léonard de Vinci" },
       { question: "Quelle est la couleur du soleil ?", answers: ["Jaune", "Bleu", "Rouge", "Blanc"], correct: "Blanc" },
       // Jeux vidéo - difficile
       { question: "Quel est le premier jeu vidéo commercialisé de l'histoire ?", answers: ["Space Invaders", "Pong", "Pac-Man", "Tennis for Two"], correct: "Pong" },
       { question: "Dans 'Dark Souls', comment s'appelle le premier boss obligatoire ?", answers: ["Taurus Demon", "Asylum Demon", "Bell Gargoyles", "Gwyn"], correct: "Asylum Demon" },
       { question: "Dans 'Earthbound', quel est le prénom du héros principal ?", answers: ["Lucas", "Ness", "Claus", "Ninten"], correct: "Ness" },
       { question: "Quel jeu est considéré comme le premier 'Metroidvania' ?", answers: ["Super Metroid", "Castlevania: Symphony of the Night", "Metroid Prime", "Castlevania II"], correct: "Castlevania: Symphony of the Night" },
       { question: "Dans 'Bloodborne', comment s'appelle la ville maudite où se déroule le jeu ?", answers: ["Lothric", "Yharnam", "Boletaria", "Anor Londo"], correct: "Yharnam" },
       { question: "Dans 'Deus Ex', quel est le nom du protagoniste cyborg ?", answers: ["JC Denton", "Adam Jensen", "Garrett", "Sam Fisher"], correct: "JC Denton" },
       { question: "Quel est le jeu qui a popularisé le genre 'Battle Royale' ?", answers: ["Fortnite", "PUBG", "H1Z1", "Call of Duty: Warzone"], correct: "PUBG" },
       { question: "Dans 'Silent Hill 2', quel est le nom du monstre iconique au casque triangulaire ?", answers: ["Pyramid Head", "Nurse", "Lying Figure", "Boogeyman"], correct: "Pyramid Head" },
       { question: "Dans 'Persona 5', sous quel pseudonyme agit le groupe des héros ?", answers: ["The Reapers", "Phantom Thieves", "Persona Users", "Midnight Crew"], correct: "Phantom Thieves" },
       { question: "Dans 'Chrono Trigger', comment s'appelle le héros principal ?", answers: ["Crono", "Serge", "Tidus", "Cloud"], correct: "Crono" },
       { question: "Quel jeu indépendant de 2017 se déroule dans un monde souterrain peuplé de bugs ?", answers: ["Undertale", "Hollow Knight", "Celeste", "Dead Cells"], correct: "Hollow Knight" },
       { question: "Dans 'The Last of Us', quel est le prénom de la jeune fille accompagnant Joel ?", answers: ["Ellie", "Sarah", "Anna", "Tess"], correct: "Ellie" },
       { question: "Dans 'Mass Effect', comment s'appelle le commandant que l'on incarne ?", answers: ["Shepard", "Garrus", "Wrex", "Anderson"], correct: "Shepard" },
       { question: "Dans 'Metroid', qui est en réalité sous l'armure de Samus Aran ?", answers: ["Un homme", "Une femme", "Un alien", "Un robot"], correct: "Une femme" },
       { question: "Quel jeu est surnommé 'le jeu maudit' pour son extrême difficulté sur NES ?", answers: ["Ghosts 'n Goblins", "Mega Man", "Ninja Gaiden", "Battletoads"], correct: "Battletoads" },
       { question: "En quelle année est sortie la première PlayStation ?", answers: ["1993", "1994", "1995", "1996"], correct: "1994" },
       { question: "Quel jeu e-sport a eu le plus gros cash prize de l’histoire (en 2021) ?", answers: ["Dota 2", "League of Legends", "CS:GO", "Fortnite"], correct: "Dota 2" },
       { question: "Comment s'appelle l'intelligence artificielle qui a battu des pros à StarCraft II ?", answers: ["AlphaGo", "DeepMind", "AlphaStar", "Skynet"], correct: "AlphaStar" },
       { question: "Dans quelle ville se tenait la première finale mondiale des Worlds de League of Legends ?", answers: ["Séoul", "Berlin", "New York", "Los Angeles"], correct: "Los Angeles" },
       { question: "Quel développeur japonais est connu pour ses jeux absurdes comme 'Katamari Damacy' ?", answers: ["Goichi Suda", "Keita Takahashi", "Tetsuya Mizuguchi", "Hidetaka Miyazaki"], correct: "Keita Takahashi" },
       { question: "Quel streamer a détenu le record du monde Twitch avec plus de 600 000 viewers en live en 2021 ?", answers: ["xQc", "Ibai", "TheGrefg", "Shroud"], correct: "TheGrefg" },
       { question: "Quel est le nom du micro-ordinateur 8 bits très populaire en Europe dans les années 80 ?", answers: ["MSX", "ZX Spectrum", "Atari ST", "Commodore 128"], correct: "ZX Spectrum" },
       { question: "Quel jeu est considéré comme le premier jeu vidéo commercialisé ?", answers: ["Pong", "Tennis for Two", "Spacewar!", "Computer Space"], correct: "Computer Space" },
       { question: "Quel jeu de la licence Final Fantasy est sorti en premier en Europe ?", answers: ["FF IV", "FF VI", "FF VII", "FF I"], correct: "FF VII" },
       { question: "Quel langage de programmation a été utilisé pour coder DOOM en 1993 ?", answers: ["C", "Assembly", "Pascal", "Fortran"], correct: "C" },
       { question: "Quel ancien champion du monde de Street Fighter est aujourd’hui commentateur e-sport ?", answers: ["Justin Wong", "Daigo Umehara", "Tokido", "Luffy"], correct: "Daigo Umehara" },
       { question: "Quel jeu e-sport a popularisé le terme 'Zerging' ?", answers: ["Warcraft III", "Command & Conquer", "StarCraft", "Dawn of War"], correct: "StarCraft" },
       { question: "Sur quelle console est sorti le jeu culte 'Chrono Trigger' ?", answers: ["NES", "Super Nintendo", "PlayStation", "Sega Saturn"], correct: "Super Nintendo" },
       { question: "Quelle console Sega proposait une manette avec un écran intégré ?", answers: ["Saturn", "Dreamcast", "Game Gear", "Nomad"], correct: "Dreamcast" },
       { question: "Quel jeu est connu pour avoir provoqué la 'crise du jeu vidéo' de 1983 ?", answers: ["Pac-Man", "E.T. the Extra-Terrestrial", "Donkey Kong Jr.", "Adventure"], correct: "E.T. the Extra-Terrestrial" },
       { question: "Quel streamer francophone est à l’origine de la Z LAN ?", answers: ["ZeratoR", "Kameto", "Doigby", "Squeezie"], correct: "ZeratoR" },
       
       // Sport - difficile
       { question: "Quel est le record du monde du 100 mètres masculin (chronométré) ?", answers: ["9.58s", "9.69s", "9.72s", "9.74s"], correct: "9.58s" },
       { question: "En quelle année la WWE a-t-elle été fondée (sous le nom WWF) ?", answers: ["1972", "1963", "1984", "1955"], correct: "1963" },
       { question: "Quel club de football a remporté le plus de Ligues des champions ?", answers: ["AC Milan", "Liverpool", "Real Madrid", "Bayern Munich"], correct: "Real Madrid" },
       { question: "Combien de tours compte un marathon officiel ?", answers: ["1", "2", "4", "Aucun, c'est une seule distance"], correct: "Aucun, c'est une seule distance" },
       { question: "Qui a été le tout premier champion olympique de l'ère moderne en 1896 ?", answers: ["Spyridon Louis", "James Connolly", "Pierre de Coubertin", "Carl Schuhmann"], correct: "James Connolly" },
       { question: "En catch, quel catcheur est connu sous le surnom de 'The Rated-R Superstar' ?", answers: ["Randy Orton", "Edge", "Jeff Hardy", "Roman Reigns"], correct: "Edge" },
       { question: "Quel club a remporté la première édition de la Ligue des Champions en 1956 ?", answers: ["Barcelone", "Milan AC", "Real Madrid", "Benfica"], correct: "Real Madrid" },
       { question: "Dans quel sport évolue l'équipe des All Blacks ?", answers: ["Football", "Basketball", "Rugby", "Cricket"], correct: "Rugby" },
       { question: "En Formule 1, quel pilote légendaire est associé au numéro 27 chez Ferrari ?", answers: ["Michael Schumacher", "Gilles Villeneuve", "Ayrton Senna", "Niki Lauda"], correct: "Gilles Villeneuve" },
       { question: "Quel lutteur a remporté le plus de titres mondiaux reconnus par la WWE ?", answers: ["Hulk Hogan", "Ric Flair", "John Cena", "Triple H"], correct: "Ric Flair" },
       { question: "Dans quel sport trouve-t-on la Ryder Cup ?", answers: ["Golf", "Tennis", "Cricket", "Polo"], correct: "Golf" },
       { question: "Quel joueur est le meilleur buteur de l'histoire de la Coupe du Monde de football ?", answers: ["Pelé", "Ronaldo", "Miroslav Klose", "Gerd Müller"], correct: "Miroslav Klose" },
       { question: "Quel pays a inventé le sport du baseball ?", answers: ["Angleterre", "États-Unis", "Cuba", "Japon"], correct: "États-Unis" },
       { question: "Quel est le surnom de Ric Flair dans le monde du catch ?", answers: ["The Nature Boy", "The Beast", "The Game", "The Phenom"], correct: "The Nature Boy" },
       { question: "Dans quel sport pratique-t-on le 'curling' ?", answers: ["Tennis", "Hockey sur glace", "Sports d'hiver", "Curling"], correct: "Curling" },
       { question: "Quelle est la distance d'un marathon officiel ?", answers: ["40 km", "42,195 km", "45 km", "50 km"], correct: "42,195 km" },
       { question: "Combien de fois Michael Schumacher a-t-il remporté le championnat du monde de F1 ?", answers: ["5", "6", "7", "8"], correct: "7" },
       { question: "Quel catcheur a remporté le Royal Rumble 2024 (WWE) ?", answers: ["Cody Rhodes", "Seth Rollins", "Roman Reigns", "Gunther"], correct: "Cody Rhodes" },
       { question: "Quel est le nom du tournoi de tennis joué sur gazon en Angleterre ?", answers: ["Roland-Garros", "Wimbledon", "US Open", "Australian Open"], correct: "Wimbledon" },


   ]

};
